version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_php
    volumes:
      - ../mountpoint/php:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    volumes:
      - ../mountpoint/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
